apiVersion: apps/v1
kind: Deployment
metadata:
  name: eyedb
  labels:
    app: eyedb
spec:
  selector:
    matchLabels:
      app: eyedb
  replicas: 1
  template:
    metadata:
      labels:
        app: eyedb
    spec:
      containers:
        - name: eyedb
          image: mongo
          volumeMounts:
            - mountPath: /var/lib/mongodb
              name: eye-db-data
          ports:
            - containerPort: 27017
              name: eyedb-port
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: eye-secret
            -  name: MONGO_INITDB_ROOT_PASSWORD
               valueFrom:
                 secretKeyRef:
                   key: MONGO_INITDB_ROOT_PASSWORD
                   name: eye-secret
      nodeSelector:
        zone: us-east-2a  # to indicate which zone we want our pods to run, should be same with the zone our volume is.
      volumes:
        - name: eye-db-data
          awsElasticBlockStore:
            volumeID: vol-05b5bb38a83254876
            fsType: ext4
      initContainers:
        - name: busybox
          image: busybox:latest
          args: [ "rm", "-rf", "/data/db/lost+found" ] # by default, aws EBS create a lost + found dir, and mongodb expect the dir to be empty, so we have to prune it first
          volumeMounts:
            - name: eye-db-data
              mountPath: /var/lib/mongodb