apiVersion: apps/v1
kind: Deployment
metadata:
  name: eyeapp
  labels:
    app: eyeapp
spec:
  selector:
    matchLabels:
      app: eyeapp
  replicas: 1
  template:
    metadata:
      labels:
        app: eyeapp
    spec:
      containers:
        - name: eyeapp
          image: 154114/server
          ports:
            - containerPort: 3000
              name: eyeapp-port
#          env:
#            - name: Mongo_URL
#              valueFrom:
#                secretKeyRef:
#                  key: Mongo_URL
#                  name: montreal-secret
#            -  name: JWT_SECRET
#               valueFrom:
#                 secretKeyRef:
#                   key: JWT_SECRET
#                   name: montreal-secret
      initContainers:
        - name: init-mydb
          image: busybox
          command: [ 'sh', '-c', 'until nslookup web-server.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;' ]
          # here we wait for the mongodb svc to start up first, as our app depends on it.